## NumPy is Linear Algebra Library for Python

### Types:
 
* **Vectors**  - **1-d Arrays**
* **Matrices** - **2-d Arrays**

In [1]:
import numpy as np

In [2]:
my_list_1d = [1,2,3]  # Single Dimensional Array



array_1d = np.array (my_list_1d)  # Casting to array

print(array_1d)

[1 2 3]


In [3]:
my_mat = [[1,2,3], [4,5,6], [7,8,9]]

mat_2d = np.array(my_mat)

print(mat_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
np.arange(0, 11, 2) # Start, End (excluded), step

array([ 0,  2,  4,  6,  8, 10])

In [5]:
np.zeros(3)

array([0., 0., 0.])

In [6]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.ones((2, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
np.linspace (0, 5, 10) # same interval (start, stop, total_no)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [9]:
# Identity Matrix

# 2d Martix which has same number of columns and rows and 1 in diagonal and 0 are in other places

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
# Matrix with Random numbers

print(np.random.rand(3)) # Single Dimensional Random number array

print('\n')

print(np.random.rand(2, 5)) # 2d Random number matrix

[0.04609846 0.78477073 0.26951003]


[[0.20203659 0.47592916 0.69700987 0.20907118 0.35426759]
 [0.61423122 0.80569042 0.88367952 0.1809794  0.70884371]]


In [11]:
# Normal Distribution Random number matrix

print(np.random.randn(3))

print('\n')

print(np.random.randn(4, 3))

[ 0.24393665 -0.21132035 -1.08095505]


[[ 0.52529295 -0.71483893 -0.37784672]
 [-1.42066355  0.79376696 -0.17335471]
 [-0.13685964  0.72527053  0.26033497]
 [-1.19731613  1.27760571 -0.40512846]]


In [12]:
np.random.randint(1, 100, 10) # Includ

array([69, 51, 38, 91, 81, 57, 86,  7, 96, 86])

In [13]:
np.random.randint(1, 100, 10).reshape(5, 2)

array([[27, 89],
       [74, 53],
       [42, 27],
       [47, 83],
       [33, 51]])

In [14]:
array = np.random.randint(1, 100, 10)

print(array)
print('max value : {}'.format(array.max()))
print('min value : {}'.format(array.min()))
print('index of min value : {}'.format(array.argmin()))
print('index of max value : {}'.format(array.argmax()))
print('data type of array : {}'.format(array.dtype))

[24 57 82 72 69 37 56 88 31 64]
max value : 88
min value : 24
index of min value : 0
index of max value : 7
data type of array : int32


### Selection and Indexing

In [15]:
array = np.arange(0, 11)

print('array : {}'.format(array))
print('8th element of array : {}'.format(array[8]))
print('1 to 5 th element of array : {}'.format(array[1:5]))
print('0 to 5 th element of array : {}'.format(array[:5]))
print('6 to n th element of array : {}'.format(array[5:]))

array : [ 0  1  2  3  4  5  6  7  8  9 10]
8th element of array : 8
1 to 5 th element of array : [1 2 3 4]
0 to 5 th element of array : [0 1 2 3 4]
6 to n th element of array : [ 5  6  7  8  9 10]


In [16]:
array_copy = array.copy()

print('array copy : {}'.format(array_copy))

array copy : [ 0  1  2  3  4  5  6  7  8  9 10]


### Matrices

In [17]:
array_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

print(f'array_2d :\n {array_2d}\n')

print(f'double bracket notation array_2d[2][1] and value is : {array_2d[2][1]}\n')
print(f'single bracket notation array_2d[2,1] and value is : {array_2d[2,1]}\n')

array_2d :
 [[ 5 10 15]
 [20 25 30]
 [35 40 45]]

double bracket notation array_2d[2][1] and value is : 40

single bracket notation array_2d[2,1] and value is : 40



In [18]:
arr = np.arange(1, 11)

print(arr)

bool_array = arr > 5

print('\nbool_array : {}'.format(bool_array))
print('\nbool_array of array : {}'.format(arr[bool_array]))

print('\narray of less than 3 : {}'.format(arr[arr < 3]))

[ 1  2  3  4  5  6  7  8  9 10]

bool_array : [False False False False False  True  True  True  True  True]

bool_array of array : [ 6  7  8  9 10]

array of less than 3 : [1 2]


### NumPy Operations

In [19]:
arr = np.arange(0, 11)

print(f'{arr}')
print(f'\naddition of array : \n {arr + arr}')

print(f'\naddition of 100 with array : \n {arr + 100}')

print(f'\nsubstraction of array : \n {arr + arr}')

print(f'\nmultipication of array : \n {arr * arr}')

print(f'\ndivision of array : \n {arr / arr}') # shows warning of nan

print(f'\ndivision of 1 / array : \n {1 / arr}') # shows warning of infinity

print(f'\npower of array : \n { arr ** 2}') 

print(f'\nsqrt of array : \n { np.sqrt(arr)}') 

print(f'\nexp of array : \n { np.exp(arr)}') 

print(f'\nsin of array : \n { np.sin(arr)}') 

[ 0  1  2  3  4  5  6  7  8  9 10]

addition of array : 
 [ 0  2  4  6  8 10 12 14 16 18 20]

addition of 100 with array : 
 [100 101 102 103 104 105 106 107 108 109 110]

substraction of array : 
 [ 0  2  4  6  8 10 12 14 16 18 20]

multipication of array : 
 [  0   1   4   9  16  25  36  49  64  81 100]

division of array : 
 [nan  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]

division of 1 / array : 
 [       inf 1.         0.5        0.33333333 0.25       0.2
 0.16666667 0.14285714 0.125      0.11111111 0.1       ]

power of array : 
 [  0   1   4   9  16  25  36  49  64  81 100]

sqrt of array : 
 [0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766]

exp of array : 
 [1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03 2.20264658e+04]

sin of array : 
 [ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:12: RuntimeWarning: invalid value encountered in true_divide
  if sys.path[0] == '':
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:14: RuntimeWarning: divide by zero encountered in true_divide
  
